# Docker Compose file for development

version: '2.1'
services:

  app:
    build: .
    command: 'node_modules/.bin/nodemon'
    depends_on:
      - mysql
      - redis
    environment:
      NODE_ENV: development # TODO: change this to 'production' on production
      PMKDATA_API_PORT: 3000
      PMKDATA_API_SECRET: "[ pmkdata_api_secret ]" # TODO: change this on production
      MYSQL_HOST: mysql
      MYSQL_USER: pmkdata
      MYSQL_PASSWORD: "[ mysql_password ]" # TODO: change this to a strong password on production, must match with mysql
      MYSQL_DATABASE: pmkdata
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "3000:3000"
    restart: 'no' # TODO: change this to 'always' on production
    volumes:
      - .:/opt/pmkdata-api
      - /opt/pmkdata-api/node_modules # Prevent mounting local node_modules

  mysql:
    image: "mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "[ mysql_root_password ]" # TODO: change this to a strong password on production, for administration purposes
      MYSQL_DATABASE: pmkdata
      MYSQL_USER: pmkdata
      MYSQL_PASSWORD: "[ mysql_password ]" # TODO: change this to a strong password on production, must match with app
    restart: 'no' # TODO: change this to 'always' on production
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: "redis:alpine"
    restart: 'no' # TODO: change this to 'always' on production

volumes:
  mysql_data:
    driver: local